CREATE TABLE Libro(
	IdLibro INT PRIMARY KEY IDENTITY(1,1),
	Titolo VARCHAR(250) NOT NULL,
	AnnoPubblicazione DATE NOT NULL,
	IsDisponibile BIT NOT NULL
);

CREATE TABLE Utente(
	IdUtente INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(250) NOT NULL,
	Cognome VARCHAR(250) NOT NULL,
	Email VARCHAR(250) NOT NULL
);

CREATE TABLE Prestito(
	IdPrestito INT PRIMARY KEY IDENTITY(1,1),
	LibroRIF INT NOT NULL,
	UtenteRIF INT NOT NULL,
	Data_inizio DATE NOT NULL,
	Data_fine DATE,
	FOREIGN KEY (LibroRIF) REFERENCES Libro(IdLibro) ON DELETE CASCADE,
	FOREIGN KEY (UtenteRIF) REFERENCES Utente(IdUtente) ON DELETE CASCADE
);

SELECT * FROM Libro;
